### ISSUE TITLE
Fails to build with GDAL 3.8.0

### ISSUE THREAD

**Issue by sebastic** [ajolma/Geo-GDAL-FFI#63]
As reported in [Debian Bug #1055581](https://bugs.debian.org/1055581):
> Your package FTBFS with GDAL 3.8.0 from experimental:
> ```
> Cannot write feature at /build/libgeo-gdal-ffi-perl-0.1/blib/lib/Geo/GDAL/FFI/Driver.pm line 49.
>         Geo::GDAL::FFI::Driver::Create(Geo::GDAL::FFI::Driver=SCALAR(0x557a150d4c40), "/vsimem/test.tiff", 10) called at t/vsistdout.t line 63
> # Tests were run but no plan was declared and done_testing() was not seen.
> # Looks like your test exited with 2 just after 1.
> t/vsistdout.t .. 
> ```
> The full buildlog is attached.
> 
> [libgeo-gdal-ffi-perl_0.1-2.1_amd64.build](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=1055581;filename=libgeo-gdal-ffi-perl_0.1-2.1_amd64.build;msg=5)

**Comment by shawnlaffan** [comment]
I can reproduce locally using GDAL 3.8.0RC1.

The error message is only associated with the geojson OGR driver in the GDAL code base.
https://github.com/search?q=repo%3AOSGeo%2Fgdal+%22Cannot+write+feature%22&type=code

Disabling the preceding test block gets the test to pass.
https://github.com/ajolma/Geo-GDAL-FFI/blob/18bfef57a572809697cb4f3ce127011437d0cefe/t/vsistdout.t#L34

Moving the failing test block so it is run first also gets the tests to pass.  

The above suggests that something is not being cleaned up in the first test block starting at L34.  I'm not sure what.  

@ajolma - any ideas?

**Comment by shawnlaffan** [comment]
Possibly something is awry with the default callback after an override has been cleared.

https://github.com/ajolma/Geo-GDAL-FFI/blob/18bfef57a572809697cb4f3ce127011437d0cefe/lib/Geo/GDAL/FFI.pm#L1718-L1731

**Comment by shawnlaffan** [comment]
> Possibly something is awry with the default callback after an override has been cleared.

That looks like a red herring as the callback is not called in the second block with the geotiff creation.

**Comment by ajolma** [comment]
I could reproduce it in a docker with clone of gdal 3.8.0. However, I don't understand why it fails. I asked Even - apparently the mail did not go to gdal-dev but to him only - and he has no recollection of anything done in that area. I'm wondering why there is not VSIStdoutUnsetRedirection to undo the effect of the previous test but the undo seems to be a bit strange.

**Comment by ajolma** [comment]
The error is somehow caused by the first test, which copies a memory layer to geojson stdout redirected to a variable. The test is ok as the geojson is ok in the variable but for some reason there's an error generated and left in the error stack. That error then is mistaken as an error in the geotiff creation. I can't yet even find where the error is generated in gdal and why.

**Comment by ajolma** [comment]
Fixed in 8eee520. The write method must return 1 if the write was succesful. The closure in FFI.pm now returns 1 also in the case the user side class does not return anything (as in the test).

**Comment by ajolma** [comment]
The reason for why I did not find where the error came from in GDAL was that I was looking at wrong branch in GDAL tree, not the master.

**Comment by sebastic** [comment]
Confirmed fixed with the changes from https://github.com/ajolma/Geo-GDAL-FFI/commit/8eee52009825a5897aecf8b1b18f79d1100fce21.

**Comment by sebastic** [comment]
> Confirmed fixed with the changes from [8eee520](https://github.com/ajolma/Geo-GDAL-FFI/commit/8eee52009825a5897aecf8b1b18f79d1100fce21).

Unfortunately not. libgeo-gdal-ffi-perl (0.1-3) contains a patch wit those changes, but the rebuild with GDAL 3.8.0 on the Debian buildds still fails (which it did not do when I tested it on my system):
```
Cannot write feature at /<<PKGBUILDDIR>>/blib/lib/Geo/GDAL/FFI/Driver.pm line 49.
	Geo::GDAL::FFI::Driver::Create(Geo::GDAL::FFI::Driver=SCALAR(0x562aed4103d8), "/vsimem/test.tiff", 10) called at t/vsistdout.t line 63
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 2 just after 1.
t/vsistdout.t .. 
```
https://buildd.debian.org/status/package.php?p=libgeo-gdal-ffi-perl

**Comment by shawnlaffan** [comment]
This is a leftover error from the JSON write.  

Ideally the source of the error would be fixed, but clearing the ```@Geo::GDAL::FFI::errors``` array at the end of the test block gets the test to pass.

The question is whether any errors should be cleared automatically when the VSI writer is closed.  Perhaps the contents should be written to STDOUT while clearing.

**Comment by shawnlaffan** [comment]
This looks like a broader problem with CopyLayer or maybe the GDAL JSON conversion process.  

I updated the test to create three features in the source layer.  However, the resulting JSON string only contains the first one.  

Calling FlushCache on the data set has no effect.  

```diff
diff --git a/t/vsistdout.t b/t/vsistdout.t
index 02be848..038ecbc 100644
--- a/t/vsistdout.t
+++ b/t/vsistdout.t
@@ -33,21 +33,32 @@ use JSON;
 # test vsistdout redirection
 if(1){
     # create a small layer and copy it to vsistdout with redirection
-    my $layer = GetDriver('Memory')->Create->CreateLayer({GeometryType => 'None'});
+    my $ds = GetDriver('Memory')->Create;
+    my $layer = $ds->CreateLayer({GeometryType => 'None'});
     $layer->CreateField(value => 'Integer');
     $layer->CreateGeomField(geom => 'Point');
+for my $i (5..7) {
     my $feature = Geo::GDAL::FFI::Feature->new($layer->GetDefn);
     $feature->SetField(value => 12);
-    $feature->SetGeomField(geom => [WKT => 'POINT(1 1)']);
+    $feature->SetGeomField(geom => [WKT => "POINT(1 $i)"]);
     $layer->CreateFeature($feature);
-
+}
+    $ds->FlushCache;
+diag 1;
+diag @Geo::GDAL::FFI::errors;
+diag "F count: " . $layer->GetFeatureCount;
     my $output = Output->new;
     my $gdal = Geo::GDAL::FFI->get_instance;
     $gdal->SetWriter($output);
     GetDriver('GeoJSON')->Create('/vsistdout')->CopyLayer($layer);
     $gdal->CloseWriter;

+diag 2;
+diag @Geo::GDAL::FFI::errors;
     my $ret = $output->output;
+diag 3;
+diag $ret;
+diag @Geo::GDAL::FFI::errors;
     ok($ret eq
        '{"type": "FeatureCollection",'.
        '"features": '.
@@ -56,8 +67,10 @@ if(1){
        '"coordinates": [ 1.0, 1.0 ] } }]}end',
     "Redirect vsistdout to write/close methods of a class.");

+@Geo::GDAL::FFI::errors = ();
 }

+
 # test Translate
 if(1){
     my $ds = GetDriver('GTiff')->Create('/vsimem/test.tiff', 10);
```

**Comment by shawnlaffan** [comment]
Found it.

The write method of the override class needs to return 1 on success, not any true value.  

This is checked for by the GDAL JSON driver:
https://github.com/OSGeo/gdal/blob/edf1ee72fccc8cb91519218a2c4e021ecd31d0f4/ogr/ogrsf_frmts/geojson/ogrgeojsonwritelayer.cpp#L338-L342


I'll work up a PR.

**Comment by shawnlaffan** [comment]
For reference, the GDAL commit that changed the return behaviour is https://github.com/OSGeo/gdal/commit/b25706ec7e51da6db15169080bdab7bf8d9f0c03
